# Generated by Django 4.2.4 on 2023-08-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_estimation', '0002_alter_product_batches_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batches_per_month',
            field=models.PositiveIntegerField(),
        ),
    ]
